
#spring配置
spring:
  application:
    name: msg
  # 环境 dev|test|prod
  profiles:
    active:
      
  jackson: # jackson时间格式化
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
      default-property-inclusion: NON_NULL
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.6:3306/flowable?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: sundun
    initial-size: 50 # 初始化大小，最小，最大
    max-active: 500 # 初始化大小，最小，最大
    min-idle: 50 # 初始化大小，最小，最大
    max-wait: 60000 # 配置获取连接等待超时的时间
    validation-query: SELECT 1 from dual
    validation-query-timeout: 6000
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    pool-prepared-statements: true # 打开PSCache，并且指定每个连接上PSCache的大小
    max-pool-prepared-statement-per-connection-size: 20
    time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    min-evictable-idle-time-millis: 100000 # 配置一个连接在池中最小生存的时间，单位是毫秒
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  #消息队列配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #开启消息发送确认
    publisher-confirms: true
    #开启发送失败退回
    publisher-returns: true
    listener:
      #开启Ack消息确认
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
        #为了将引起异常的消息存入死信队列，该项必须配置为false
        default-requeue-rejected: false
        retry:
          #开启重试功能
          enabled: true
          #最大重试次数5次
          max-attempts: 5
          #重试间隔时间2秒
          initial-interval: 2000
        #并发消费者初始值
        concurrency: 20
        #并发消费者最大值
        max-concurrency: 50
        #每个消费者可拉取的消息数量
        prefetch: 1
  #redis配置
  redis:
    host: 192.168.1.6
    port: 6379
    password: sundun
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 50      # 连接池中的最大空闲连接
        min-idle: 10       # 连接池中的最小空闲连接
  data:
    mongodb:
      host: 192.168.1.6
      port: 27111
      database: zbg
  #data:
    #mongodb:
      #uri: mongodb://sundun:sundun@192.168.1.6:27111/zbg
  
#OAuth2配置
security:
  oauth2:
    resource:
      id: msg
      user-info-uri: http://localhost:1999/uaa/user
      prefer-token-info: false
      
zfbh:
  kafka:
    topic:
      log:
        login: sundun-log-login
        oper: sundun-log-oper
  mongo:
    collection:
      login-log: log_login
      oper-log: log_oper
      pendig-task-msg: PendigTaskMsg
      work-remind-msg: WorkRemindMsg