
#spring配置
spring:
  application:
    name: zfbh-com

#OAuth2配置
security:
  oauth2:
    resource:
      id: com
      user-info-uri: http://localhost:1999/uaa/user
      prefer-token-info: false
