
#spring配置
spring:
  application:
    name: zfbh-log
  kafka:
    consumer:
      enable-auto-commit: true
      group-id: applog
      auto-offset-reset: latest
      bootstrap-servers: 192.168.1.200:9092,192.168.1.201:9092,192.168.1.202:9092

#OAuth2配置
security:
  oauth2:
    resource:
      id: log
      user-info-uri: http://localhost:1999/uaa/user
      prefer-token-info: false