
#spring配置
spring:
  application:
    name: zfbh-biz-ywpz

#OAuth2配置
security:
  oauth2:
    resource:
      id: aj
      user-info-uri: http://localhost:1999/uaa/user
      prefer-token-info: false
