
#调试模式
debug: false

#服务器配置
server:
  max-http-header-size: 4048576
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: -1

#Spring配置
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100Mb
      max-request-size: 1000Mb
  resources:
    static-locations: classpath:/META-INF/resources/webjars/,classpath:/static/,classpath:/resources/,classpath:/public/
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
  datasource:
    name: jdbc/rdp_bz
    jndi: java:comp/env/jdbc/rdp_bz
    url: jdbc:oracle:thin:@192.168.1.11:1521:zfbh
    username: rdp_bz
    password: sundun    
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: oracle.jdbc.OracleDriver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    exceptionSorter: true
    testOnReturn: false
    poolPreparedStatement: true
    filters: stat,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMills=500
    useGlobalDataSourceStat: true
  redis:
    host: 192.168.1.6
    port: 6379
    password: sundun
    database: 1
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  kafka:
    producer:
      bootstrap-servers: 192.168.1.6:9092
      retries: 0
      batch-size: 4096
      buffer-memory: 40960
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    mongodb:
      host: 192.168.1.6
      port: 27111
      database: zbg
  #data:
   # mongodb:
    #  uri: mongodb://sundun:sundun@192.168.1.200:27017/zbg

mybatis-plus:
  mapper-locations:
    - classpath*:mapper/v*/**/*.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: -1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    #sql日志打印 生产环境不开启
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#执法闭环配置
zfbh:
  kafka:
    topic:
      log:
        login: sundun-log-login
        oper: sundun-log-oper
  mongo:
    collection:
      login-log: log_login
      oper-log: log_oper
  dic:
    uploadUrl: http://localhost:999/upload/dic
    downloadUrl: http://localhost:999/dic/

#服务发现注册配置
eureka:
  instance:
    prefer-ip-address: true #使用IP注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    health-check-url-path: /actuator/health
  client:
    serviceUrl:
      #服务中心配置
      defaultZone: http://localhost:1901/eureka/

#熔断隔离配置
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000

#feign 默认关闭熔断，请看HystrixFeignConfiguration
feign:
  hystrix:
    enabled: true

#监控端点配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  security:
    enabled: false

#OAuth2配置
security:
  oauth2:
    swagger:
      clientId: swagger
      clientSecret: sundun-swagger
